old_sound_rabbit_mq:
  connections:
    default:
      host: "%env(resolve:RABBITMQ_HOST)%"
      port: "%env(resolve:RABBITMQ_PORT)%"
      user: "%env(resolve:RABBITMQ_USER)%"
      password: "%env(resolve:RABBITMQ_PASSWORD)%"

  producers:
    mailer:
      connection: default
      exchange_options:
        name: 'mailer_exchange'
        type: direct

  consumers:
    mailer:
      connection: default
      exchange_options:
        name: 'mailer_exchange'
        type: direct
      queue_options:
        name: 'mailer_queue'
      callback: AppBundle\Mailer\MailerConsumer